FROM openjdk:11-jdk-stretch
WORKDIR /src/muzix
ADD /target/Zuul-Micro-Service-0.0.1-SNAPSHOT.jar /src/muzix/Zuul-Micro-Service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "Zuul-Micro-Service-0.0.1-SNAPSHOT.jar"]